services:
- type: web
  name: testhasura
  plan: free
  env: docker
  autoDeploy: false
  healthCheckPath: /healthz
  envVars:
  - key: HASURA_GRAPHQL_DATABASE_URL
    fromDatabase:
      name: testhasura
      property: connectionString
  - key: HASURA_GRAPHQL_ENABLE_CONSOLE
    value: true
  - key: PORT
    value: 10000
  - key: HASURA_GRAPHQL_ADMIN_SECRET
    generateValue: true
databases:
- name: testhasura
  postgresMajorVersion: 14
